- name: Checkout
  uses: actions/checkout@v3.4.0

- name: Cache
  uses: actions/cache@v2.1.8
  
- name: Unity - Test runner
  uses: game-ci/unity-test-runner@v2.1.1

- name: Unity - Builder
  uses: game-ci/unity-builder@v2.2.0

